meta:
  enabled: true
  path: /v1/telephony/config/locations/{locationId}

calling:
  enabled: false

  dialing:
    enabled: true

    internalDialing:
      enabled: true
      path: /v1/telephony/config/locations/{locationId}/internalDialing

  callHandling:
    enabled: true

    outgoingPermission:
      enabled: true
      path: /v1/telephony/config/locations/{locationId}/outgoingPermission

    musicOnHold:
      enabled: true
      path: /v1/telephony/config/locations/{locationId}/musicOnHold

    intercept:
      enabled: true
      path: /v1/telephony/config/locations/{locationId}/intercept

    callRecording:
      enabled: true

      provider:
        enabled: true
        path: /v1/telephony/config/callRecording

      announcements:
        enabled: true
        path: /v1/telephony/config/locations/{locationId}/callRecording/announcements

      complianceAnnouncement:
        enabled: true
        path: /v1/telephony/config/locations/{locationId}/callRecording/complianceAnnouncement

      emergencyCalls:
        enabled: true
        path: /v1/telephony/config/locations/{locationId}/callRecording/emergencyCalls

  callingFeatures:
    enabled: true

    voicemail:
      enabled: true
      path: /v1/telephony/config/locations/{locationId}/voicemail

    callCaptions:
      enabled: true
      path: /v1/telephony/config/locations/{locationId}/callCaptions

    voicePortal:
      enabled: true
      path: /v1/telephony/config/locations/{locationId}/voicePortal

    hotDesking:
      enabled: true
      path: /v1/telephony/config/locations/{locationId}/features/hotDesking

    schedules:
      enabled: true
      path: /v1/telephony/config/locations/{locationId}/schedules

    callPark:
      enabled: true
      path: /v1/telephony/config/locations/{locationId}/callParks/settings

  deviceManagement:
    enabled: true

    deviceSettings:
      enabled: true
      path: /v1/telephony/config/locations/{locationId}/devices/settings

pstn:
  enabled: false

  pstnConfiguration:
    enabled: true

    mainNumber:
      enabled: true
      resolve:
        from: meta.callingLineId.phoneNumber
        path: /v1/telephony/config/numbers?number={value}
        single: true
        key: phoneNumbers

  emergencyCalling:
    enabled: true

    callbackNumber:
      enabled: true
      path: /v1/telephony/config/locations/{locationId}/features/emergencyCallbackNumber

    emergencyCallNotification:
      enabled: true
      path: /v1/telephony/config/locations/{locationId}/emergencyCallNotification

devices:
  enabled: false
  resolve:
    from: meta.id
    path: /v1/devices?locationId={value}

workspaces:
  enabled: false
  resolve:
    from: meta.id
    path: /v1/workspaces?locationId={value}
    key: items

huntGroups:
  enabled: false
  resolve:
    from: meta.id
    path: /v1/telephony/config/huntGroups?locationId={value}
    key: huntGroups

callParkExtensions:
  enabled: false
  resolve:
    from: meta.id
    path: /v1/telephony/config/callParkExtensions?locationId={value}
    key: callParkExtensions

callParkGroups:
  enabled: false
  resolve:
    from: meta.id
    path: /v1/telephony/config/locations/{value}/callParks
    key: callParks

callPickup:
  enabled: false
  resolve:
    from: meta.id
    path: /v1/telephony/config/locations/{value}/callPickups
    key: callPickups