global_settings:
  features.callerId.customNumber: "{General Inquiries}"
  features.callerId.externalCallerIdNamePolicy: "LOCATION"
  license.name: "Webex Calling - Workspaces"
  devices.length: "1"

extensions:
  # Pharmacy:
  "3350":
    callHandling.callForwarding.busy.destination: "3351"
    callHandling.callForwarding.busy.enabled: true
    callHandling.callWaiting.enabled: false
    features.callerId.customNumber: "{IVR}"
    features.callerId.dialByName: "LD{storenumber} Pharmacy - 3350"
    license.name: "Webex Calling - Professional"
    meta.displayName: "LD{storenumber} Pharmacy - 3350"

  "3351":
    meta.displayName: "LD{storenumber} Pharmacy - 3351"
    features.callerId.dialByName: "LD{storenumber} Pharmacy - 3351"
    features.callerId.customNumber: "{IVR}"
    callHandling.callForwarding.busy.enabled: true
    callHandling.callForwarding.busy.destination: "3352"
    callHandling.callWaiting.enabled: false
    license.name: "Webex Calling - Professional"

  "3352":
    meta.displayName: "LD{storenumber} Pharmacy - 3352"
    features.callerId.dialByName: "LD{storenumber} Pharmacy - 3352"
    features.callerId.customNumber: "{IVR}"
    callHandling.callWaiting.enabled: false
    license.name: "Webex Calling - Professional"

  "3370":
    meta.displayName: "LD{storenumber} Pharmacy - 3370"
    features.callerId.dialByName: "LD{storenumber} Pharmacy - 3370"
    features.callerId.customNumber: "{IVR}"
    license.name: "Webex Calling - Professional"

  "6010":
    meta.displayName: "LD{storenumber} Pharmacy - 6010"
    features.callerId.dialByName: "LD{storenumber} Pharmacy - 6010"
    features.callerId.customNumber: "{IVR}"

  "6020":
    meta.displayName: "LD{storenumber} Pharmacy - 6020"
    features.callerId.dialByName: "LD{storenumber} Pharmacy - 6020"
    features.callerId.customNumber: "{IVR}"

  "6030":
    meta.displayName: "LD{storenumber} Pharmacy - 6030" 
    features.callerId.dialByName: "LD{storenumber} Pharmacy - 6030"
    features.callerId.customNumber: "{IVR}"

  "6040":
    meta.displayName: "LD{storenumber} Pharmacy - 6040"
    features.callerId.dialByName: "LD{storenumber} Pharmacy - 6040"
    features.callerId.customNumber: "{IVR}"

  "6050":
    meta.displayName: "LD{storenumber} Pharmacy - 6050"
    features.callerId.dialByName: "LD{storenumber} Pharmacy - 6050"
    features.callerId.customNumber: "{IVR}"

  "6051":
    meta.displayName: "LD{storenumber} Pharmacy - 6051"
    features.callerId.dialByName: "LD{storenumber} Pharmacy - 6051"
    features.callerId.customNumber: "{IVR}"

  "6061":
    meta.displayName: "LD{storenumber} Pharmacy - 6061"
    features.callerId.dialByName: "LD{storenumber} Pharmacy - 6061"
    features.callerId.customNumber: "{IVR}"

  "6062":
    meta.displayName: "LD{storenumber} Pharmacy - 6062"
    features.callerId.dialByName: "LD{storenumber} Pharmacy - 6062"
    features.callerId.customNumber: "{IVR}"

  "6063":
    meta.displayName: "LD{storenumber} Pharmacy - 6063"
    features.callerId.dialByName: "LD{storenumber} Pharmacy - 6063"
    features.callerId.customNumber: "{IVR}"

  "6064":
    meta.displayName: "LD{storenumber} Pharmacy - 6064"
    features.callerId.dialByName: "LD{storenumber} Pharmacy - 6064"
    features.callerId.customNumber: "{IVR}"

  "6290":
    meta.displayName: "LD{storenumber} Pharmacy - 6290"
    features.callerId.dialByName: "LD{storenumber} Pharmacy - 6290"
    features.callerId.customNumber: "{IVR}"
    license.name: "Webex Calling - Professional"

  "6360":
    meta.displayName: "LD{storenumber} Pharmacy - 6360"
    features.callerId.dialByName: "LD{storenumber} Pharmacy - 6360"
    features.callerId.customNumber: "{IVR}"

  "6370":
    meta.displayName: "LD{storenumber} Pharmacy - 6370"
    features.callerId.dialByName: "LD{storenumber} Pharmacy - 6370"
    features.callerId.customNumber: "{IVR}"
  
  # TECH:
  "6060":
    meta.displayName: "LD{storenumber} Computers - 6060"
    features.callerId.dialByName: "LD{storenumber} Computers - 6060"
    features.callerId.customNumber: "{TECH}"

  "6070":
    meta.displayName: "LD{storenumber} Computers - 6070"
    features.callerId.dialByName: "LD{storenumber} Computers - 6070"
    features.callerId.customNumber: "{TECH}"

  "6080":
    meta.displayName: "LD{storenumber} Computers - 6080"
    features.callerId.dialByName: "LD{storenumber} Computers - 6080"
    features.callerId.customNumber: "{TECH}"

  "6240":
    meta.displayName: "LD{storenumber} Cameras - 6240"
    features.callerId.dialByName: "LD{storenumber} Cameras - 6240"
    features.callerId.customNumber: "{TECH}"

  "6430":
    meta.displayName: "LD{storenumber} Cameras Lockup - 6430"
    features.callerId.dialByName: "LD{storenumber} Cameras Lockup - 6430"
    features.callerId.customNumber: "{TECH}"

  "6450":
    meta.displayName: "LD{storenumber} AVS Lockup - 6450"
    features.callerId.dialByName: "LD{storenumber} AVS Lockup - 6450"
    features.callerId.customNumber: "{TECH}"

  "6530":
    meta.displayName: "LD{storenumber} Cameras - 6530"
    features.callerId.dialByName: "LD{storenumber} Cameras - 6530"
    features.callerId.customNumber: "{TECH}"

  "6531":
    meta.displayName: "LD{storenumber} Cameras - 6531"
    features.callerId.dialByName: "LD{storenumber} Cameras - 6531"
    features.callerId.customNumber: "{TECH}"

  "6532":
    meta.displayName: "LD{storenumber} Cameras - 6532"
    features.callerId.dialByName: "LD{storenumber} Cameras - 6532"
    features.callerId.customNumber: "{TECH}"

  # Cosmetics:
  "6100":
    meta.displayName: "LD{storenumber} Cosmetics - 6100"
    features.callerId.dialByName: "LD{storenumber} Cosmetics - 6100"
    features.callerId.customNumber: "{Curbside}"

  "6101":
    meta.displayName: "LD{storenumber} Cosmetics - 6101"
    features.callerId.dialByName: "LD{storenumber} Cosmetics - 6101"
    features.callerId.customNumber: "{Curbside}"
    
  "6102":
    meta.displayName: "LD{storenumber} Cosmetics - 6102"
    features.callerId.dialByName: "LD{storenumber} Cosmetics - 6102"
    features.callerId.customNumber: "{Curbside}"

  # Customer Service:
  "6190":
    meta.displayName: "LD{storenumber} CUS - 6190"
    features.callerId.dialByName: "LD{storenumber} CUS - 6190"

  "6200":
    meta.displayName: "LD{storenumber} CUS - 6200"
    features.callerId.dialByName: "LD{storenumber} CUS - 6200"

  "6210":
    meta.displayName: "LD{storenumber} CUS - 6210"
    features.callerId.dialByName: "LD{storenumber} CUS - 6210"

  "6110":
    meta.displayName: "LD{storenumber} Lane 1 - 6110"
    features.callerId.dialByName: "LD{storenumber} Lane 1 - 6110"

  "6120":
    meta.displayName: "LD{storenumber} Lane 2 - 6120"
    features.callerId.dialByName: "LD{storenumber} Lane 2 - 6120"

  "6130":
    meta.displayName: "LD{storenumber} Lane 3 - 6130"
    features.callerId.dialByName: "LD{storenumber} Lane 3 - 6130"

  "6140":
    meta.displayName: "LD{storenumber} Lane 4 - 6140"
    features.callerId.dialByName: "LD{storenumber} Lane 4 - 6140"

  "6150":
    meta.displayName: "LD{storenumber} Lane 5 - 6150"
    features.callerId.dialByName: "LD{storenumber} Lane 5 - 6150"

  "6160":
    meta.displayName: "LD{storenumber} Lane 6 - 6160"
    features.callerId.dialByName: "LD{storenumber} Lane 6 - 6160"

  "6170":
    meta.displayName: "LD{storenumber} Lane 7 - 6170"
    features.callerId.dialByName: "LD{storenumber} Lane 7 - 6170"

  "6180":
    meta.displayName: "LD{storenumber} Lane 8 - 6180"
    features.callerId.dialByName: "LD{storenumber} Lane 8 - 6180"

  # Photo Finishing
  "6250":
    meta.displayName: "LD{storenumber} Photo - 6250"
    features.callerId.dialByName: "LD{storenumber} Photo - 6250"
    features.callerId.customNumber: "{Photo Finishing}"

  "6260":
    meta.displayName: "LD{storenumber} Photo - 6260"
    features.callerId.dialByName: "LD{storenumber} Photo - 6260"
    features.callerId.customNumber: "{Photo Finishing}"

  "6230":
    meta.displayName: "LD{storenumber} LAB - 6230"
    features.callerId.dialByName: "LD{storenumber} LAB - 6230"
    features.callerId.customNumber: "{Photo Finishing}"

  "6500":
    meta.displayName: "LD{storenumber} LAB - 6500"
    features.callerId.dialByName: "LD{storenumber} LAB - 6500"
    features.callerId.customNumber: "{Photo Finishing}"

  # Canada Post
  "6800":
    meta.displayName: "LD{storenumber} CPC - 6800"
    features.callerId.dialByName: "LD{storenumber} CPC - 6800"
    features.callerId.customNumber: "{Canada Post}"

  "6801":
    meta.displayName: "LD{storenumber} CPC - 6801"
    features.callerId.dialByName: "LD{storenumber} CPC - 6801"
    features.callerId.customNumber: "{Canada Post}"

  # Insurance:
  "6701":
    features.callerId.customNumber: "{Insurance}"
    features.callerId.dialByName: "LD{storenumber} INS - 6701"
    meta.displayName: "LD{storenumber} INS - 6701"

  "6702":
    features.callerId.customNumber: "{Insurance}"
    features.callerId.dialByName: "LD{storenumber} INS - 6702"
    meta.displayName: "LD{storenumber} INS - 6702"

  "6703":
    features.callerId.customNumber: "{Insurance}"
    features.callerId.dialByName: "LD{storenumber} INS - 6703"
    meta.displayName: "LD{storenumber} INS - 6703"

  "6704":
    features.callerId.customNumber: "{Insurance}"
    features.callerId.dialByName: "LD{storenumber} INS - 6704"
    meta.displayName: "LD{storenumber} INS - 6704"

  "6705":
    features.callerId.customNumber: "{Insurance}"
    features.callerId.dialByName: "LD{storenumber} INS - 6705"
    meta.displayName: "LD{storenumber} INS - 6705"

  # Manager & SPC
  "6000":
    meta.displayName: "LD{storenumber} Manager - 6000"
    features.callerId.dialByName: "LD{storenumber} Manager - 6000"
    callHandling.callForwarding.busy.enabled: true
    callHandling.callForwarding.busy.destination: "6929"
    callHandling.callForwarding.noAnswer.enabled: true
    callHandling.callForwarding.noAnswer.destination: "6929"

  "6001":
    meta.displayName: "LD{storenumber} Manager - 6001"
    features.callerId.dialByName: "LD{storenumber} Manager - 6001"
    callHandling.callForwarding.busy.enabled: true
    callHandling.callForwarding.busy.destination: "6929"
    callHandling.callForwarding.noAnswer.enabled: true
    callHandling.callForwarding.noAnswer.destination: "6929"

  "6300":
    meta.displayName: "LD{storenumber} CR - 6300"
    features.callerId.dialByName: "LD{storenumber} CR - 6300"

  "6330":
    meta.displayName: "LD{storenumber} SPC - 6330"
    features.callerId.dialByName: "LD{storenumber} SPC - 6330"

  "6350":
    meta.displayName: "LD{storenumber} Supervisor - 6350"
    features.callerId.dialByName: "LD{storenumber} Supervisor - 6350"

  # Paging
  "6991":
    meta.displayName: "LD{storenumber} Night Ringer - 6991"
    features.callerId.dialByName: "LD{storenumber} Night Ringer - 6991"
    features.callerId.customNumber: ""
    devices.length: "0"

  "6994":
    meta.displayName: "LD{storenumber} Paging - 6994"
    features.callerId.dialByName: "LD{storenumber} Paging - 6994"
    features.callerId.customNumber: ""

  "6995":
    meta.displayName: "LD{storenumber} Emergency - 6995"
    features.callerId.dialByName: "LD{storenumber} Emergency - 6995"
    features.callerId.customNumber: ""
    devices.length: "0"

  "6999":
    meta.displayName: "LD{storenumber} Doorbell - 6999"
    features.callerId.dialByName: "LD{storenumber} Doorbell - 6999"
    features.callerId.customNumber: ""
    devices.length: "0"

  #Receiving
  "6310":
    meta.displayName: "LD{storenumber} Verification - 6310"
    features.callerId.dialByName: "LD{storenumber} Verification - 6310"

  "6311":
    meta.displayName: "LD{storenumber} Ecomm - 6311"
    features.callerId.dialByName: "LD{storenumber} Ecomm - 6311"

  "6320":
    meta.displayName: "LD{storenumber} Receiving - 6320"
    features.callerId.dialByName: "LD{storenumber} Receiving - 6320"

  "6321":
    meta.displayName: "LD{storenumber} Receiving - 6321"
    features.callerId.dialByName: "LD{storenumber} Receiving - 6321"

  # Loss Prevention
  "6340":
    meta.displayName: "LD{storenumber} LP - 6340"
    features.callerId.dialByName: "LD{storenumber} LP - 6340"

  "6341":
    meta.displayName: "LD{storenumber} LP - 6341"
    features.callerId.dialByName: "LD{storenumber} LP - 6341"

  # Optical
  "6810":
    meta.displayName: "LD{storenumber} Optical - 6810"
    features.callerId.dialByName: "LD{storenumber} Optical - 6810"
    features.callerId.customNumber: "{Optical}"

  "6811":
      meta.displayName: "LD{storenumber} Optical - 6811"
      features.callerId.dialByName: "LD{storenumber} Optical - 6811"
      features.callerId.customNumber: "{Optical}"